import GithubCorner from '@/components/GithubCorner';
import './globals.scss';
import ParticlesJs from '@/components/ParticlesJs';

export const metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
    return (
        <html lang="en">
            <body>
                <ParticlesJs />
                <GithubCorner />
                {children}
            </body>
        </html>
    );
}
